### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS when decoding fileId.

### ISSUE THREAD

**Issue by butthx** [smaznet/tg-file-id#3]
Hi, i am trying to make a file id for photo from gramjs. 
Then i try to decode the file id, i got `RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds`. 

Is there something wrong with my code?

```ts 
interface generateFileId {
  version: number;
  subVersion: number;
  dcId: number;
  fileType: string | number;
  id: string;
  accessHash: string;
  typeId: number;
  fileReference: string;
  url?: string;
  volumeId?: number | bigint;
  localId?: number ;
  photoSizeSource?: 'legacy' | 'thumbnail' | 'dialogPhoto' | 'stickerSetThumbnail';
  photoSizeSourceId?: number;
  secret?: number;
  dialogId?: number;
  dialogAccessHash?: number;
  isSmallDialogPhoto?: boolean;
  stickerSetId?: number ;
  stickerSetAccessHash?: number;
  thumbType?: string;
  thumbTypeId?: number;
}
function generateFileId(medias:generateFileId){
  let file = new FileId() 
  for(let [key,value] of Object.entries(medias)){
      if(key == "id" || key == "accessHash" || key == "secret"){
        file[key] = BigInt(value)
      }else{
        file[key] = value
      }
  }
  console.log(file)
  let file_id = file.toFileId()
  let unfId = file.toFileUniqId()
  return {
    fileId : file_id,
    uniqueFileId : unfId
  }
}
let file = generateFileId({
  version : Math.floor(Math.random() * 20),
  subVersion : Math.floor(Math.random() * 20), 
  dcId : message.media.photo.dcId,
  fileType : "photo",
  id : String(message.media.photo.id),
  accessHash : String(message.media.photo.accessHash),
  typeId : 2,
  fileReference : message.media.photo.fileReference.toString("hex")
})
// AgACAgUAAxkBAAOQYQMowjoE3vg6RlL745DpKjBQ7JMAAhitMRsXjRBUvEdUCJDwohUPEA 
console.log(decodeFileId(file.fileId))
```

Thanks for your respon.

**Comment by smaznet** [comment]
accessHash and id should be bigInt

```js
  id : BigInt(message.media.photo.id),
  accessHash : BigInt(message.media.photo.accessHash),
```

**Comment by butthx** [comment]
its already convert to BigInt 
```ts
if(key == "id" || key == "accessHash" || key == "secret"){
   file[key] = BigInt(value)
}
```

**Comment by butthx** [comment]
Hi i ask. 
Can accessHash be prefixed with a minus (-) sign?
i got this error : 
```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0n and < 2n ** 64n. Received -1_792_358_012_146_714_198n
```
`"accessHash": "-1792358012146714198"`
I got the accessHash from json gramjs.

**Comment by smaznet** [comment]
@butthx yes accessHash is signed integer :thinking:

**Comment by butthx** [comment]
> @butthx yes accessHash is signed integer 🤔

oh okay, but I get an error when the accessHash is prefixed with a minus sign. 
```ts
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0n and < 2n ** 64n. Received -1_792_358_012_146_714_198n
    at checkInt (internal/buffer.js:69:11)
    at writeBigU_Int64LE (internal/buffer.js:576:3)
    at Buffer.writeBigUInt64LE (internal/buffer.js:598:10)
    at Function.to64bitBuffer (/data/data/com.termux/files/home/tgsnake/node_modules/tg-file-id/src/Util.ts:162:9)
    at FileId.toFileId (/data/data/com.termux/files/home/tgsnake/node_modules/tg-file-id/src/FileId.ts:116:17)
    at generateFileId (/data/data/com.termux/files/home/tgsnake/src/snake/rewritejson.ts:310:22)
    at new Media (/data/data/com.termux/files/home/tgsnake/src/snake/rewritejson.ts:259:23)
    at /data/data/com.termux/files/home/tgsnake/tes/index.ts:71:17
    at step (/data/data/com.termux/files/home/tgsnake/tes/index.ts:40:23)
    at Object.next (/data/data/com.termux/files/home/tgsnake/tes/index.ts:21:53) {
  code: 'ERR_OUT_OF_RANGE'
}
```
gramjs json : 
```ts
VirtualClass {
  CONSTRUCTOR_ID: 2628808919,
  SUBCLASS_OF_ID: 1198308914,
  className: 'MessageMediaDocument',
  classType: 'constructor',
  flags: 1,
  document: VirtualClass {
    CONSTRUCTOR_ID: 512177195,
    SUBCLASS_OF_ID: 555739168,
    className: 'Document',
    classType: 'constructor',
    flags: 1,
    id: Integer { value: 6147479595202380226n },
    accessHash: Integer { value: -1792358012146714198n },
    fileReference: <Buffer 01 00 00 00 9a 61 04 74 a1 35 e6 1f ab b0 64 ee af 1d 8e 55 2c e8 90 36 68>,
    date: 1621735354,
    mimeType: 'image/webp',
    size: 12710,
    thumbs: [ [VirtualClass], [VirtualClass] ],
    videoThumbs: null,
    dcId: 5,
    attributes: [ [VirtualClass], [VirtualClass], [VirtualClass] ]
  },
  ttlSeconds: null
}
```
is there any solution to solve it?
